### ISSUE TITLE
Aggiungere nel setup del database gli allergeni

### ISSUE THREAD

**Issue by lucagasperini** [lucagasperini/PickyEaters#26]

**Comment by CristianaGiustiniani** [comment]
Ho fatto una distinzione fra Allergia ed Allergene.

Allergia non la ho toccata.

Ho creato la tabella Allergene, quella di raccordo fra l'allergene e gli ingredienti dove è contenuto, e quella dove ci sono le descrizioni specifiche dell'allergene (che non so se useremo nell'applicazione, ma comunque le ho messe).
Ho creato la procedure per ottenere dal nome di un allergene il suo id.
Ho istanziato la popolazione delle tre tabelle e ho modificato la tua popolazione di Ingrediente, aggiungendo/rivedendo l'organizzazione delle istanze di ingredienti.

Fammi sapere se è quello che intendevi, così eventualmente chiudo l'issue @lucagasperini.

**Comment by lucagasperini** [comment]
Le tabelle c'erano già, serviva solo mettere gli allergeni con la procedura `add_allergy()`

**Comment by lucagasperini** [comment]
Risolto con merge #66
