### ISSUE TITLE
Centrare Start view

### ISSUE THREAD

**Issue by lucagasperini** [lucagasperini/PickyEaters#47]

**Comment by CristianaGiustiniani** [comment]
Non ho capito quale fossero gli elementi che ti creano problemi, nel dubbio ho comunque fatto dei cambiamenti. Fammi sapere se posso chiudere l'issue @lucagasperini

**Comment by lucagasperini** [comment]
> Non ho capito quale fossero gli elementi che ti creano problemi, nel dubbio ho comunque fatto dei cambiamenti. Fammi sapere se posso chiudere l'issue @lucagasperini

Intendevo abbassare verso il centro la Start View, come era nelle versioni precedenti?

![Screenshot_20240207_142718](https://github.com/lucagasperini/PickyEaters/assets/118215832/2f3ae0d1-81db-44ed-8e85-5fee01d376b2)

**Comment by lucagasperini** [comment]
Poi aumentare lo spazio dalla view, se pensi che sia meglio centrarla
